### PR TITLE
Added error prop without breaking changes to status flag

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**
There were some duplicates in the styling between default and error, so I created a mixin that has styling common to the two classes and it can also take a status parameter to know when to style a css property (e.g border-bottom as error or default)

### CODE REVIEW

**Review by kaf-lamed-beyt — APPROVED** [review]
These changes are freaking awesome!

I love the Sass mixins approach. Thank you so much for contributing! 🚀

**Comment by Emmanuel-Develops** [comment]
> These changes are freaking awesome!
> 
> I love the Sass mixins approach. Thank you so much for contributing! 🚀

Thanks for your kind words. This is my first contribution to any open source repo

**Comment by kaf-lamed-beyt** [comment]
> Thanks for your kind words. This is my first contribution to any open source repo

I'm glad it was a smooth process for you. Please feel free to suggest any improvements that you think can be added to the project.

**Comment by kaf-lamed-beyt** [comment]
@Emmanuel-Develops did an awesome job of thinking through the process of removing redundant styles and adding a new prop for the modal. @all-contributors add @Emmanuel-Develops for code

**Pull request merged**
